### ISSUE TITLE
Ubuntu instalation problem

### ISSUE THREAD

**Issue by woles** [ekatzenstein/create-react-app-fullstack#1]
After command fullstack:

bash: /usr/local/bin/fullstack: /usr/local/bin/node^M:bad interpreter: No such file or directory

**Comment by ekatzenstein** [comment]
@woles Thanks for posting this. Line endings issue, resolved with new version.

**Comment by shivshankardayal** [comment]
It should be /usr/bin/env node as you are forcing node to be in /usr/loca/bin which may not be the choice of user.
