### ISSUE TITLE
Requires running `npm run build` once before any other command.

### ISSUE THREAD

**Issue by mkuipers** [ekatzenstein/create-react-app-fullstack#3]
The first time I ran `npm run start` I got the following error: 
```
Error: ENOENT: no such file or directory, stat '/Users/maxkuipers/work/whos_moving_2/build/index.html'
    at Error (native)
```

It fixed itself after I ran `npm run build` once.  I am unable to reproduce the problem even if I remove the `build` directory.

**Comment by ekatzenstein** [comment]
@mkuipers Resolved with new version. Closing now.
